#define DEFINE_CONST(s) rb_define_const(cLDAP, #s, INT2NUM(s))

/* options */
DEFINE_CONST(LDAP_OPT_API_FEATURE_INFO);
DEFINE_CONST(LDAP_OPT_API_INFO);
DEFINE_CONST(LDAP_OPT_CLIENT_CONTROLS);
DEFINE_CONST(LDAP_OPT_CONNECT_ASYNC);
DEFINE_CONST(LDAP_OPT_CONNECT_CB);
DEFINE_CONST(LDAP_OPT_DEBUG_LEVEL);
DEFINE_CONST(LDAP_OPT_DEFBASE);
DEFINE_CONST(LDAP_OPT_DEREF);
DEFINE_CONST(LDAP_OPT_DESC);
DEFINE_CONST(LDAP_OPT_DIAGNOSTIC_MESSAGE);
DEFINE_CONST(LDAP_OPT_HOST_NAME);
DEFINE_CONST(LDAP_OPT_MATCHED_DN);
DEFINE_CONST(LDAP_OPT_NETWORK_TIMEOUT);
DEFINE_CONST(LDAP_OPT_PROTOCOL_VERSION);

/* errors */
DEFINE_CONST(LDAP_SUCCESS);
DEFINE_CONST(LDAP_OPERATIONS_ERROR);
DEFINE_CONST(LDAP_PROTOCOL_ERROR);
DEFINE_CONST(LDAP_TIMELIMIT_EXCEEDED);
DEFINE_CONST(LDAP_SIZELIMIT_EXCEEDED);
